// CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_ONE_QUANTITY = 'REMOVE_ONE_QUANTITY';
export const ADD_ONE_QUANTITY = 'ADD_ONE_QUANTITY';
export const CHECKOUT = 'CHECKOUT';
// PRODUCTLIST
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE';
// PRODUCT
export const LIKE_PRODUCT = 'LIKE_PRODUCT';
export const DISLIKE_PRODUCT = 'DISLIKE_PRODUCT';
